### ISSUE TITLE
All uses of DescriptionType should maybe be minOccurs="0" maxOccurs="unbounded"

### ISSUE THREAD

**Issue by mhoganRiff** [MESAInternational/B2MML-BatchML#62]
There are 218 uses of DescriptionType in the B2MML standard. Of these 218 uses, 210 have the cardinality minOccurs="0" maxOccurs="unbounded"

The remaining eight uses of the DescriptionType declare the cardinality as minOccurs = 0. Since the default for "maxoccurs" is 1, this makes the Description element effectively an "optional" entity in these eight cases. 

In B2MML 6.0, the cases are:
TransChangeStatusType, OperationsMaterialBillType, OperationsMaterialBillItemType, OperationsSegmentType, ManufacturingBillType, ProductSegmentType, BatchEquipmentRequirementType, BatchParameterType

If the cardinality were changed to minOccurs="0" maxOccurs="unbounded", it would be a little more consistent, and it would not spoil backward compatibility. Existing, valid BatchML documents would remain valid with the new declarations.

**Comment by Dennis-Brandl** [comment]
This will be changed in the soon to be released. 
Changes made in: TransChangeStatusType, OperationsMaterialBillType, OperationsMaterialBillItemType, OperationsSegmentType, BatchEquipmentRequirementType, BatchParameterType, 
The following elements were removed in version 0700:  ManufacturingBillType, ProductSegmentType because the Product Definition schema was removed. 

Thank you
Dennis
