### ISSUE TITLE
The enumeration "ResourceLocationType1Type" repeats the "Equipment" field 

### ISSUE THREAD

**Issue by BigVulcanDeal** [MESAInternational/B2MML-BatchML#75]
In B2MML-Common.xsd, the ResourceLocationType1Type repeats the field "Equipment

    <xsd:complexType name="ResourceLocationType1Type">
        <xsd:simpleContent>
            <xsd:restriction base="CodeType">
                <xsd:enumeration value="Operational Location ID"/>
                <xsd:enumeration value="Operational Location"/>
                <xsd:enumeration value="Equipment"/>
                <xsd:enumeration value="Person"/>
                <xsd:enumeration value="Equipment"/>
                <xsd:enumeration value="Physical Asset"/>
                <xsd:enumeration value="Description"/>
                <xsd:enumeration value="Other"/>
            </xsd:restriction>
        </xsd:simpleContent>
    </xsd:complexType>

**Comment by BigVulcanDeal** [comment]
After looking a little closer, I assume that one of these "Equipment" entries should be something else .. "Material" comes to mind ..

**Comment by gerardmoloneyetpartners** [comment]
Actually, if we read the documentation a few lines down, it explains the enumeration list. 
![image](https://user-images.githubusercontent.com/54049079/215014335-cb1f5447-7139-49ef-9c38-ff7c6b001b53.png)

In all likelihood, the list was probably copied from somewhere, and instead of deleting the 'material' its been changed to 'equipment' and introduced the duplicate in the list. 

I vote for deleting line 1572 to remove the duplicate.
There is no need to reference something being stored in, or required to move inside a MaterialLot. So a Material reference in the ResourceLocationType1Type is not required, as per the documentation.

**Comment by Dennis-Brandl** [comment]
I will remove.
